name: chatbots
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  # Main dependencies available through conda
  - pydantic=2.10.5
  - python-dotenv=1.0.1
  - rich=13.9.4
  - tenacity=8.5.0
  # Development dependencies
  - black=24.10.0
  - hatch=1.14.0
  - hatchling=1.25.0
  - isort=5.13.2
  - pylint=3.2.7
  - pytest=7.4.4
  - pytest-cov=6.0.0
  # Packages that need pip
  - pip:
    - anthropic==0.42.0
    - google.generativeai==0.8.3
    - ollama==0.4.5
    - openai==1.59.6
    - tomlcheck=0.2.3
    - pipreqs=0.5.0
    - mypy=1.11.2
    - mypy-extensions=1.0.0
