[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chatbot_conversation"
version = "0.1.0"
description = "A chatbot conversation system"
authors = [{name = "Brian Sentance", email = "brian@sentance.tech"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "openai>=1.12.0",
    "anthropic>=0.18.1",
    "google-generativeai>=0.3.2",
    "ollama>=0.1.7",
    "python-dotenv>=1.0.0",
    "typing-extensions>=4.9.0"
]

[tool.hatch.build.targets.wheel]
packages = ["chatbot_conversation"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
line-length = 88
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
strict = true
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = [".", "src"]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v -s"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]






